import time
from datetime import datetime

def generate_netscape_html(organized_bookmarks):
    """
    Generates a Netscape Bookmark HTML string for export.
    organized_bookmarks: List of dicts with 'category', 'title', 'url'
    """
    
    # 1. Group by Category
    categories = {}
    for bm in organized_bookmarks:
        cat = bm.get("category", "Uncategorized")
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(bm)
        
    # 2. Build HTML
    html_lines = [
        "<!DOCTYPE NETSCAPE-Bookmark-file-1>",
        "<!-- This is an automatically generated file.",
        "     It will be read and overwritten.",
        "     DO NOT EDIT! -->",
        "<!-- Generated by AI Browser Organizer -->",
        "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">",
        "<TITLE>Bookmarks</TITLE>",
        "<H1>Bookmarks</H1>",
        "<DL><p>"
    ]
    
    # Sort categories alphabetically
    sorted_cats = sorted(categories.keys())
    
    for cat_path in sorted_cats:
        # Handle Nested Categories (Simple approach: Create a flat folder structure for now to avoid deep recursion complexity)
        # Ideally, we split by " > " and create nested DLs. 
        # For this version, we will just use the full string as the folder name or basic nesting.
        
        # Let's try basic nesting support
        parts = cat_path.split(' > ')
        indent = "    "
        
        # For simplicity in this first robust pass, we create one folder per unique category string.
        # Deep nesting reconstruction is complex for a flat list.
        
        html_lines.append(f"{indent}<DT><H3 ADD_DATE=\"{int(time.time())}\">{cat_path}</H3>")
        html_lines.append(f"{indent}<DL><p>")
        
        for bm in categories[cat_path]:
            title = bm.get("title", "No Title")
            url = bm.get("url", "#")
            # Escape HTML special chars? (Minimal for now)
            title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            
            html_lines.append(f"{indent}    <DT><A HREF=\"{url}\" ADD_DATE=\"{int(time.time())}\">{title}</A>")
            
        html_lines.append(f"{indent}</DL><p>")

    html_lines.append("</DL><p>")
    
    return "\n".join(html_lines)
